### ISSUE TITLE
Using NSTimeInterval for page view duration causes reports of days in use rather than seconds

### ISSUE THREAD

**Issue by ryanholden8** [Microsoft/ApplicationInsights-iOS#115]
Hi,

Title sums it up. What is the time measurement we should be using? Documentation does not specify. The example uses 300, is that 300 seconds? aka NSTimeInterval or 300 milliseconds? The API type is (long).. why not use the standard NSTimeInterval objc type?

Thanks for your time!

**Comment by chrwend** [comment]
Thank you for reporting this bug. We are going to fix this issue as soon as possible.

-Christoph

From: Ryan Holden
Reply-To: Microsoft/ApplicationInsights-iOS
Date: Monday 10 August 2015 07:36
To: Microsoft/ApplicationInsights-iOS
Subject: [ApplicationInsights-iOS] Using NSTimeInterval for page view duration causes reports of days in use rather than seconds (#115)


Hi,

Title sums it up. What is the time measurement we should be using? Documentation does not specify. The example uses 300, is that 300 seconds? aka NSTimeInterval or 300 milliseconds? The API type is (long).. why not use the standard NSTimeInterval objc type?

Thanks for your time!

**Comment by chrwend** [comment]
Hi Ryan, thanks for reporting! We are going to fix that issue as soon as possible.

@lukasspiess: Seems like we are sending the wrong value to the server. Instead of sending the milliseconds we are supposed to send the duration in TimeSpan "G" (general long) format: d:hh:mm:ss.fffffff

**Comment by chrwend** [comment]
Method signatures with the `duration`parameter won't be supported in the future. This won't be fixed.

**Comment by ryanholden8** [comment]
@chrwend Can I request a explanation on this? I'm somewhat confused.. Will the iOS SDK not support a duration property or will it be automatic?

**Comment by ryanholden8** [comment]
@chrwend Sorry to ask again, but this is a important metric for page views and currently it does not work, has no work around, and close to a month with no response as to a solution.

Is there another way to track duration on page views?

**Comment by anlinde** [comment]
@ryanholden8 We don't have any plans to support this use case now or in the future. I am sorry, but we can't provide any more information on this.

**Comment by ryanholden8** [comment]
Hi @chrwend @anlinde @lumaxis,

Somewhat confused.. I just saw PR #131 come in that addresses this issue.

Couple questions arise in my mind:
1. I'm wondering why this ticket was closed? This leads me to believe other tickets that are closed on this project are in reality still open.
2. Is the duration parameter for pageView events still going away as stated by @chrwend?

**Comment by lumaxis** [comment]
@ryanholden8:
1. We changed our plans slightly and decided release a minor bugfix release soon that fixes some of the most prevalent issues with this SDK
2. It will eventually but while it's still here, we thought it should at least work :)

**Comment by ryanholden8** [comment]
Ah I see, appreciate the reply. Thanks! @lumaxis
