### ISSUE TITLE
Bitcode

### ISSUE THREAD

**Issue by JessicaYeh** [Microsoft/ApplicationInsights-iOS#132]
When I tried compiling an app with the app insights SDK it said I need to disable bitcode, but bitcode is required to be on (for all targets, even the main app, I read) for a project that has a watch app :(

**Comment by lumaxis** [comment]
Hey @JessicaYeh 🙂
According to this [documentation](https://developer.apple.com/library/tvos/documentation/IDEs/Conceptual/AppDistributionGuide/AppThinning/AppThinning.html#//apple_ref/doc/uid/TP40012582-CH35-SW2) Bitcode is still optional for all iOS targets. We couldn't support Bitcode earlier because downloading the symbol files necessary for symbolication of crash reports simply did not work. Even now, although this works, it makes crash reporting more tedious and complicated.
That said, we plan to release a final maintenance update for this SDK this or next week which will enable Bitcode. After that, the SDK will not be supported any longer.

**Comment by JessicaYeh** [comment]
Hi Lukas :) Thank you!!
