### ISSUE TITLE
Tracing with specific severity

### ISSUE THREAD

**Issue by AverageAsker** [Microsoft/ApplicationInsights-iOS#136]
There is an enum [MSAISeverityLevel](https://github.com/Microsoft/ApplicationInsights-iOS/blob/a7e642063893b403bad8e6920cd1764a6362ec99/Classes/MSAISeverityLevel.h) which defines severities but there are no samples showing its usage and a search through sources didn't bring more clarity. Is it in use? Can you show how it should be used with, for instance, trackTraceWithMessage? 
I should be able to choose specific severity while sending messages to App Insights server. And I would expect to see messages created with severity Error or Critical in the Portal's section named Failures.
Are these valid asks?

**Comment by TroubleMakerBen** [comment]
Hi AverageAsker,

Thanks for getting in touch.
There's currently no API to use the MSAISeverityLevel. Plans have changed since the SDK launched, please read the [official blogpost](https://azure.microsoft.com/en-us/blog/transitioning-mobile-apps-from-application-insights-to-hockeyapp/) about the transition to HockeyApp.
If you still want to use the ApplicationInsights-iOS SDK and need something like MSAISeverityLevel, you'll have to fork the SDK.

Cheers,
Benjamin
